Things

diff --git a/scripts/markdown b/scripts/markdown
--- a/scripts/markdown
+++ b/scripts/markdown
@@ -1,6 +1,6 @@
 #!/bin/bash
 
 echo "Build: started"
-pandoc --standalone --citeproc $@ || { echo "build failed"; exit 1; }
+pandoc --standalone --filter pandoc-xnos --citeproc $@ || { echo "build failed"; exit 1; }
 echo "Build: complete"
 
